SELECT
  NULL AS TABLE_CAT,
  TABLES.OWNER AS TABLE_SCHEM,
  TABLES.TABLE_NAME AS TABLE_NAME,
  TABLES.TABLE_TYPE AS TABLE_TYPE,
  TABLES.COMMENTS AS REMARKS
FROM
  ALL_TAB_COMMENTS TABLES
  INNER JOIN USER_USERS USERS
    ON TABLES.OWNER = USERS.USERNAME
      AND NOT REGEXP_LIKE(USERS.USERNAME, '^APEX_[0-9]{6}$')
      AND NOT REGEXP_LIKE(USERS.USERNAME, '^FLOWS_[0-9]{5}$')
WHERE 
  REGEXP_LIKE(TABLES.OWNER, 'ADMACI')
  AND TABLES.TABLE_NAME NOT LIKE 'BIN$%'
  AND NOT REGEXP_LIKE(TABLES.TABLE_NAME, '^(SYS_IOT|MDOS|MDRS|MDRT|MDOT|MDXT)_.*$')
  AND (TABLES.TABLE_NAME LIKE 'ACI_D_VEICULO' 
  OR TABLES.TABLE_NAME LIKE 'ACI_D_CORRETOR'
  OR TABLES.TABLE_NAME LIKE 'ACI_D_CLIENTE'
  OR TABLES.TABLE_NAME LIKE 'ACI_D_GERENTE' 
  OR TABLES.TABLE_NAME LIKE 'ACI_D_PRODUTO'
  OR TABLES.TABLE_NAME LIKE 'ACI_D_UF') 